import React from "react";
import { TodoItem } from "./TodoItem";
export const Todos = (props) => {
	const myTodoStyle = {
		minHeight: "40vh",
		margin: "40px auto",
	};
	return (
		<div className="container" style={myTodoStyle}>
			<h3 className="my-3">Todos List</h3>
			{props.todos.length === 0 ? (
				// If there are no todo in todos
				<div className="container">
					<p> There is no todo </p>
					<p> You can add todo in todo list by filling the form above</p>
				</div>
			) : (
				// If there are todo in todos
				// <p> There is todo </p>
				props.todos.map((todo, index) => {
					//index is not entered here but generated by map method itself here we just specify that we are going to use the index
					return (
						<TodoItem
							todo={todo}
							key={todo.srno}
							// index={todo.srno - 1}
							index={index}
							onDelete={props.onDelete}
							isCompleted={todo.isCompleted}
							// checkTodoByIndex={props.checkTodoByIndex}
							changeCompleted={props.changeCompleted}
						/>
					);
				})
			)}
		</div>
	);
};
